## Project working guidance

- Read `docs/project-status.md` for the verified baseline, representative files, source findings, and unresolved decisions. Follow the path rules discovered through `.ai/rules/index.md`, including the feature-branch and focused-commit workflow in `.ai/rules/general.md`.
- Multi-tenancy, roles/permissions, and user management are implemented and tested by the project owner for current use cases. Build on them. Distinguish owner verification, agent checks, stated requirements, and source observations; onboarding observations and paused proposals are not an implementation backlog.
- Check installed versions and use matching Laravel, Filament, and Livewire documentation through Boost. Inspect the returned package/version; an unrelated or wrong-major search result is not authority. Frontend manifest ranges are not installed versions; verify a lockfile or installed metadata when available.
- Reuse neighboring implementations and the established resource, model, and policy boundaries, including the existing Shield/Spatie authorization integration. Do not add architectural layers, dependencies, formatting standards, or broad refactors without a concrete task need. If an existing pattern causes a specific correctness or security problem relevant to the requested feature, explain the evidence and propose the smallest appropriate change.
- For custom UI work, use `frontend-design` when available while preserving the existing visual identity and Blade/Livewire/Tailwind stack. For Filament work, prioritize native components and supported customization mechanisms; consult the existing panel and switcher before adding UI.
- Activate relevant available Superpowers workflows: brainstorming for new behavior, planning/execution for substantial implementation, systematic debugging for failures, test-driven development for behavior changes, and review plus verification before completion. Apply them within the authorized scope and reuse the feature branch; a workflow or worktree is not a reason to create a branch per subtask. Do not modify global Superpowers installations or resolve duplicate skills as incidental work.
- Follow `.editorconfig` and neighboring code. Strict types, broader formatting normalization, and policy record-parameter signatures remain unresolved; generated general typing advice does not settle those choices. Keep any formatter changes limited to the task's files.
- Use the existing PHPUnit tooling and adapt generated Pest examples to PHPUnit and `Livewire::test()` instead of installing Pest. The checked-in starter tests do not describe the full extent of the owner's testing.
- Before database or tenant tests, verify effective isolated connections, disposable tenant databases/storage, hostname and permission fixtures, and cleanup. Tenant lifecycle events create, migrate, and delete databases; SQLite `:memory:` alone does not establish safe multidatabase isolation.
- Do not run `composer run setup` as routine onboarding: it generates an application key and force-runs migrations. Do not expose environment secrets. Keep unrelated work and custom guidance intact.
- Maintain these instructions in `.ai/guidelines/project.blade.php`; regenerate with `php artisan boost:install --guidelines --skills --no-interaction` and review the diff. Use Boost's `record-rule` tool for durable path rules and preserve its generated index. Keep detailed evidence and open decisions in `docs/project-status.md`, not repeated throughout the generated guidance.
